### ISSUE TITLE
Challenges encountered during the reproduction of your experiment

### ISSUE THREAD

**Issue by rimawiz** [emsec/unsupervised-ic-sem-segmentation#1]
Dear all,

I trust this message finds you in good health.

I want to express my sincere gratitude for your efforts and for sharing your paper and project codes with us. We, as master's students, are keen to utilize your paper to replicate the work.

We have attempted to use Google Colab and Kaggle for this purpose. However, we encountered some obstacles. Google Colab lacks OpenCL and can't be installed, which is essential for running your code. Additionally, in Kaggle, your code requires numpy version 1.17, as indicated by the following error message:
"ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.
"
Traceback (most recent call last):
  File "/kaggle/working/unsupervised-ic-sem-segmentation/train.py", line 4, in <module>
    import libs.datasets as datasets
  File "/kaggle/working/unsupervised-ic-sem-segmentation/libs/datasets.py", line 8, in <module>
    from torchvision.transforms import functional as F
  File "/opt/conda/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/opt/conda/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/opt/conda/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/opt/conda/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "/opt/conda/lib/python3.10/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "/opt/conda/lib/python3.10/site-packages/torch/onnx/__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "/opt/conda/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 42, in <module>
    from torch.onnx._internal.fx import (
  File "/opt/conda/lib/python3.10/site-packages/torch/onnx/_internal/fx/__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "/opt/conda/lib/python3.10/site-packages/torch/onnx/_internal/fx/patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
  File "/opt/conda/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/opt/conda/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/versions.py", line 39, in _compare_versions
    raise ValueError(
ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.
"

We kindly seek your assistance in resolving the aforementioned issues so that we can successfully execute the code on either Google Colab or Kaggle. Your guidance and support in this matter would be greatly appreciated. Thank you.

**Comment by nproth** [comment]
Hi,

thanks for your interest in our work. I unfortunately don't have much experience with either of these platforms and can't really help with them. Your kaggle error message though looks like there is either a package version mismatch, in which case you can try newer numpy versions, or a misconfiguration of your Python environment (there are some Stackoverflow and Github posts on this error). If you have access to a GPU that supports PyTorch and OpenCL, our ML model is also small enough to train locally, given an appropriate `--batch_split` (32 worked for me on a GPU with 8GB VRAM).

Hope this helps and best regards
Nils
